services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./www/html:/var/www/html
    depends_on:
      - portfolio
      - shop
    restart: always

  portfolio:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: portfolio-db
      WORDPRESS_DB_NAME: portfolio
      WORDPRESS_DB_USER: riki
      WORDPRESS_DB_PASSWORD: ${RIKI_PASS}
    volumes:
      - ./www/portfolio:/var/www/html
    restart: always

  portfolio-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: riki
      MYSQL_PASSWORD: ${RIKI_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - portfolio_db_data:/var/lib/mysql
    restart: always

  shop:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: shop-db
      WORDPRESS_DB_NAME: shop
      WORDPRESS_DB_USER: riki
      WORDPRESS_DB_PASSWORD: ${RIKI_PASS}
    volumes:
      - ./www/shop:/var/www/html
    restart: always

  shop-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: riki
      MYSQL_PASSWORD: ${RIKI_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - shop_db_data:/var/lib/mysql
    restart: always

volumes:
  portfolio_db_data:
  shop_db_data:
