server {
    listen 80;
    server_name portfolio.localhost;

    location / {
        proxy_pass http://portfolio:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto http;
    }
}

server {
    listen 80;
    server_name shop.localhost;

    location / {
        proxy_pass http://shop:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto http;
    }
}

server {
    listen 80;
    server_name localhost www.localhost;

    location / {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}